################################################################################################################################################################

MRFFL_PATH = ..

include $(MRFFL_PATH)/make_includes/tools_gfortran.mk
# include $(MRFFL_PATH)/make_includes/tools_flang.mk
# include $(MRFFL_PATH)/make_includes/tools_ifx.mk
# include $(MRFFL_PATH)/make_includes/tools_lfortran.mk
# include $(MRFFL_PATH)/make_includes/tools_nvfortran.mk

include $(MRFFL_PATH)/make_includes/include.mk

################################################################################################################################################################

clean : clean_multi_mrffl
	rm -f *~

clean_docs : 
	rm -rf autodocs
